main: neutron.App
package: neutron
version: 0.0.1
description: Neutron - A lightweight JavaFX native webview app framework
language: java
scripts:
  start: jpm compile && jpm run
  compile@: jpm compile && jpm cp
  cp: cp -r resources/* out/
  clean: rm -rf out/* dist 
  dev: jpm run -hot "(resources/**|neutron/*)" "jpm cp"
  install@: jpm install:{{jpm.OS-ARCH}} ...args@
  install:windows-amd64: JFX=win jpm install ...args@
  install:darwin-amd64: JFX=mac jpm install ...args@
  install:darwin-arm64: JFX=mac-aarch64 jpm install ...args@
  install:linux-amd64: JFX=linux jpm install ...args@
dependencies:
  - org.openjfx javafx-web:21.0.8
  - com.fasterxml.jackson.core jackson-databind:latest
classifiers:
  org.openjfx: '{{ENV.JFX}}'
repos:
  - default: https://repo1.maven.org/maven2/
args:
  java: --add-modules javafx.controls,javafx.graphics,javafx.web
