main: neutron.App
package: neutron
version: 0.0.0
language: java
scripts:
  start: jpm compile && jpm run
  compile@: jpm compile && jpm cp
  cp: cp -r resources/* out/
  clean: rm -rf out/* dist 
  dev: jpm run -hot "(resources/ui/*|neutron/*)" "jpm cp && jpm compile!"
  dev:ui: cd ui && npm run dev
  install@: jpm install:{{jpm.OS-ARCH}} ...args@
  install:windows-amd64: JFX=win jpm install ...args@
  install:darwin-amd64: JFX=mac jpm install ...args@
  install:darwin-arm64: JFX=mac-aarch64 jpm install ...args@
  install:linux-amd64: JFX=linux jpm install ...args@
dependencies:
  - org.openjfx javafx-web:21.0.8
  - io.reactivex.rxjava3 rxjava:3.1.12
  - com.fasterxml.jackson.core jackson-databind:latest
  - concurrently:1.0.0 exec
classifiers:
  org.openjfx: '{{ENV.JFX}}'
repos:
  - default: https://repo1.maven.org/maven2/
args:
  java: --enable-preview --add-modules javafx.controls,javafx.graphics,javafx.web
  javac: --enable-preview --release 21
